name: Tag Commit Workflow

on:
  push:
    branches:
      - main

jobs:
  tag-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name '9c-liveAsset-ci'
          git config --global user.email 'dev.sonohoshi@gmail.com'
          
      - name: Fetch all tags
        run: git fetch --tags

      - name: Delete existing tag
        run: |
          if git rev-parse -q --verify "refs/tags/Release"; then
            git tag -d Release
            git push origin :refs/tags/Release
          fi

      - name: Tag the commit
        run: |
          git tag Release
          git push origin Release
